site_name: Lucidchart User Documentation

nav:
  - Home: index.md
  - General Operations: pages/Shuyi_create_share_export.md
  - Formatting Shapes: pages/Olga_formatting_shapes.md
  - Formatting Lines: pages/Olga_formatting_lines.md
  - Troubleshooting: pages/Shuyi_Troubleshooting.md
  - Glossary: pages/Shuyi_Glossary.md

repo_url: https://github.com/olgazim/LucidChart-User-Documentation

repo_name: olgazim/LucidChart-User-Documentation

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - toc:
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables

